server:
  port: 8761
# 유레카 서버가 웹서비스의 성격으로서 기동이 된다.
# 해당 서비스의 포트번호를 어떻게 정의할 것인가를 설정한다.

spring:
  application:
    name: discoveryservice
# 마이크로 서비스의 key/value 쌍을 등록한다고 했다.
#이때 서버 네임은 id 값으로 작용하기 때문에 임의로 설정한다.

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# 서버를 기동하는데 프로젝트에 유레카가 포함되어 기동이 되면
# 서버는 클라이언트로서 자신의 key/value 를 테이블에 등록하게 된다.
# 하지만 위의 두 속성에 대해서 true 로 두게 되면 자기 자신을 자기 자신의 테이블에 등록하는
# 작업이 진행이 되어지기 때문에 true -> fals e로 정의한다.

# 즉,유레카 서버로서만 가동이 되어지고 다른 마이크로 서비스와 데이터를 주고받을
# 일이 없기 때문에 그냥 말그대로 서버로서 띄워져 있으면 된다고 한다.